### ISSUE TITLE
Pin or upgrade code to work with Hishel 1.0

### ISSUE THREAD

**Issue by Owen-OptiGrid** [owenlamont/uv-secure#129]
I think Hishel 1.0 has made some breaking changes I need to deal with.

```shell
uv-secure................................................................Failed
- hook id: uv-secure
- exit code: 1
  Traceback (most recent call last):
    File "/home/runner/.cache/prek/hooks/python-1Dmmj6XivEV4MECZ2yOB/bin/uv-secure", line 4, in <module>
      from uv_secure.run import app
    File "/home/runner/.cache/prek/hooks/python-1Dmmj6XivEV4MECZ2yOB/lib/python3.13/site-packages/uv_secure/__init__.py", line 2, in <module>
      from uv_secure.run import app
    File "/home/runner/.cache/prek/hooks/python-1Dmmj6XivEV4MECZ2yOB/lib/python3.13/site-packages/uv_secure/run.py", line 8, in <module>
      from uv_secure.dependency_checker import check_lock_files, RunStatus
    File "/home/runner/.cache/prek/hooks/python-1Dmmj6XivEV4MECZ2yOB/lib/python3.13/site-packages/uv_secure/dependency_checker/__init__.py", line 1, in <module>
      from uv_secure.dependency_checker.dependency_checker import (
      ...<4 lines>...
      )
    File "/home/runner/.cache/prek/hooks/python-1Dmmj6XivEV4MECZ2yOB/lib/python3.13/site-packages/uv_secure/dependency_checker/dependency_checker.py", line 10, in <module>
      from hishel import AsyncCacheClient, AsyncFileStorage
  ImportError: cannot import name 'AsyncCacheClient' from 'hishel' (/home/runner/.cache/prek/hooks/python-1Dmmj6XivEV4MECZ2yOB/lib/python3.13/site-packages/hishel/__init__.py)
```

**Comment by owenlamont** [comment]
I'll try and have a fix out ASAP, sorry for the hassle this is causing (it's been a pain for me to with pre-commit installs).
